#### 
# Register User
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Njenga David",
  "email": "njengadavid111@gmail.com",
  "password": "39667871#Davy",
  "isAdmin": 0
}
#### Login User
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "josephmuhia@gmail.com",
  "password": "joseph@1!"
}
// get all the users
######
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMxMjAzLCJleHAiOjE3MTg2Mzg0MDN9.XELymKrYQ885sNgAhiy1KChix4fhGYXEX857iC4SSnM
//Add Tours
####
POST http://localhost:4000/tours
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w
Content-Type: application/json

{
  "name": "Lake Nakuru",
  "description": "good views at nakuru",
  "price": 1500,
  "duration": 1
}
// Get all tours
####
GET http://localhost:4000/tours
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w

#### get a single tour
GET http://localhost:4000/tour/0a5c3157-7df6-4a47-adee-44da671a47af
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w


// add hotel
####
POST http://localhost:4000/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w
Content-Type: application/json

{
  "name": "Mimshark Hotel",
  "location": "Nyeri",
  "price": 2500
}

//Get all hotels
####
GET http://localhost:4000/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJlYTBjNzU5My0xYjkyLTQ3MjUtODNiNC0yMTkxZGNmZGI0MjQiLCJOYW1lIjoiSmFuZXQgQW55b25hIiwiaXNBZG1pbiI6MSwiaWF0IjoxNzE4NjMyNTY5LCJleHAiOjE3MTg2Mzk3Njl9.Gq5Et2N6nfp3YnYhlATNe3ekxXynzHMRhDO2EEwXU-w







